export const CART_ADD_ITEM = "CART_ADD_ITEM"
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM"

export const CART_CHANGE_ITEM_QUANTITY = "CART_CHANGE_ITEM_QUANTITY"


export const SAVE_SHIPPING_ADDRESS_SUCCESS = "SAVE_SHIPPING_ADDRESS_SUCCESS"
export const SAVE_SHIPPING_ADDRESS_REQUEST = "SAVE_SHIPPING_ADDRESS_REQUEST"
export const SAVE_SHIPPING_ADDRESS_FAIL = "SAVE_SHIPPING_ADDRESS_FAIL"

