
export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST"
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS"
export const PLACE_ORDER_FAIL = "PLACE_ORDER_FAIL"


export const SINGLE_ORDER_DETAILS_REQUEST = "SINGLE_ORDER_DETAILS_REQUEST"
export const SINGLE_ORDER_DETAILS_SUCCESS = "SINGLE_ORDER_DETAILS_SUCCESS"
export const SINGLE_ORDER_DETAILS_FAIL = "SINGLE_ORDER_DETAILS_FAIL"
export const SINGLE_ORDER_DETAILS_RESET = "SINGLE_ORDER_DETAILS_RESET"




export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST"
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS"
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL"
export const ORDER_LIST_RESET = "ORDER_LIST_RESET"




export const ADMIN_ORDER_LIST_REQUEST = "ADMIN_ORDER_LIST_REQUEST"
export const ADMIN_ORDER_LIST_SUCCESS = "ADMIN_ORDER_LIST_SUCCESS"
export const ADMIN_ORDER_LIST_FAIL = "ADMIN_ORDER_LIST_FAIL"




export const ADMIN_ORDER_UPDATE_REQUEST = "ADMIN_ORDER_UPDATE_REQUEST"
export const ADMIN_ORDER_UPDATE_SUCCESS = "ADMIN_ORDER_UPDATE_SUCCESS"
export const ADMIN_ORDER_UPDATE_FAIL = "ADMIN_ORDER_UPDATE_FAIL"



export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST"
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS"
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL"
export const ORDER_PAY_RESET = "ORDER_PAY_RESET"

